export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS";
export const ALL_BLOG_FAIL = "ALL_BLOG_FAIL";

export const MY_BLOG_REQUEST = "MY_BLOG_REQUEST";
export const MY_BLOG_SUCCESS = "MY_BLOG_SUCCESS";
export const MY_BLOG_FAIL = "MY_BLOG_FAIL";

export const NEW_BLOG_REQUEST = "NEW_BLOG_REQUEST";
export const NEW_BLOG_SUCCESS = "NEW_BLOG_SUCCESS";
export const NEW_BLOG_RESET = "NEW_BLOG_RESET";
export const NEW_BLOG_FAIL = "NEW_BLOG_FAIL";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";

export const UPVOTE_BLOG_REQUEST = "UPVOTE_BLOG_REQUEST";
export const UPVOTE_BLOG_SUCCESS = "UPVOTE_BLOG_SUCCESS";
export const UPVOTE_BLOG_FAIL = "UPVOTE_BLOG_FAIL";

export const COMMENT_BLOG_REQUEST = "COMMENT_BLOG_REQUEST";
export const COMMENT_BLOG_SUCCESS = "COMMENT_BLOG_SUCCESS";
export const COMMENT_BLOG_FAIL = "COMMENT_BLOG_FAIL";

export const DEL_COMMENT_BLOG_REQUEST = "DEL_COMMENT_BLOG_REQUEST";
export const DEL_COMMENT_BLOG_SUCCESS = "DEL_COMMENT_BLOG_SUCCESS";
export const DEL_COMMENT_BLOG_FAIL = "DEL_COMMENT_BLOG_FAIL";


export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";

export const REVOKE_BLOG_REQUEST = "REVOKE_BLOG_REQUEST";
export const REVOKE_BLOG_SUCCESS = "REVOKE_BLOG_SUCCESS";
export const REVOKE_BLOG_RESET = "REVOKE_BLOG_RESET";
export const REVOKE_BLOG_FAIL = "REVOKE_BLOG_FAIL";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
