import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'
import style2 from '@/styles/About.module.css'
const inter = Inter({ subsets: ['latin'] })
const slug = () => {
    const router = useRouter();
    const { slug } = router.query;
    const [blog , setBlog] = useState(null);
    const [loading , setLoading] = useState(true);
    console.log(slug);
    const fetchData = async()=>{
        try{
            const res = await fetch(`http://localhost:4000/api/v1/blog/${slug}`);
            const data = await res.json();
            if(data.success){
                setBlog(data.blog);
                setLoading(false);
            }else{
                console.error(data.message);
                router.replace('/');
            }
        }catch(error){
            console.error(error);
            
        }
    }
    useEffect(()=>{
        if(slug){
            fetchData();
        }
    },[slug])
    return (
        <>
        {loading? <div style={{minHeight:"100vh",display:"flex",alignItems:"center",justifyContent:"center",color:"white"}}>Loading</div>:
        <>
            <Head>
                <title>{blog.name}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div className="drop-shadow-[0_10px_150px_rgba(255,255,255,1)] flex items-center justify-center w-[90vw] min-h-[90vh] gap-[20px] flex-col border border-gray-700 py-[50px]" >
                    <h1 className='text-5xl'>{blog.name}</h1>
                    <h3 className='text-slate-500' >By <Link href={"users/" + blog.user.userName}>{blog.user.userName}</Link></h3>
                    <p className={style2.para + " " + ""}>{blog.desc}</p>
                    <p className={style2.para + " " + ""}>{blog.content}</p>
                </div>
                <div className='flex py-[25px] pb-[5px] flex-col border border-gray-700 mt-[20px] min-h-[500px] w-[90vw]'>
                    <h1 className='text-3xl self-center'>Comments</h1>
                    <div className='flex flex-col w-[100%] px-[20px] py-[20px] gap-[10px] border-t border-gray-700 mt-[25px]'>
                        {blog.comments.map((i, index) => (
                            <div className='flex flex-col w-[100%] px-[10px] gap-[10px] border-b pb-[10px] border-gray-700' i={i} key={index}>
                                <h3 className='text-slate-500' >{i.user.userName}</h3>
                                <p className='overflow-auto h-fit min-h-[20px]'>{i.content}</p>
                            </div>
                        ))}
                        
                    </div>
                </div>
            </main>
        </>
        }
        </>
    )
};
 
export default slug;