import React from 'react'
import Navbar from '@/src/navbar'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Footer from '@/src/footer'
import style2 from '@/styles/About.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function About(){
  return (
    <>
        <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center} style={{display:`flex` ,gap:`20px`, flexDirection:'column'}}>
          <h1 style={{fontSize:"9em"}}>About</h1>
          <p className={style2.para}>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
      </main>
    </>
  )
}
