import React from 'react'
import Navbar from '@/src/navbar'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/src/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Blogs(){
  return (
    <>
        <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1 style={{fontSize:"5em"}}>Blogs</h1>
        </div>
      </main>
    </>
  )
}
