import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/src/navbar'
import Footer from '@/src/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1 style={{fontSize:"5em"}}>BlogPost</h1>
        </div>

        <div className={styles.grid}>
          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about everything you need in Blogs using&nbsp;BlogPost.
            </p>
          </a>

          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about varous things in each and every blog with&nbsp;BlogPost!
            </p>
          </a>

          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover boilerplate example&nbsp;projects.
            </p>
          </a>

          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Post <span>-&gt;</span>
            </h2>
            <p>
              Instantly post your Next Blog Page to a shareable URL
              with&nbsp;BlogPost.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
