import Head from 'next/head'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const appRef = useRef();
  const [defaultVar , setDefault] = useState(0);
  useEffect(()=>{
    try{
      if(defaultVar == 0){
        if(appRef){
          appRef.current.style.setProperty(
            '--mouse-x',
            0 + "%"
          )
          appRef.current.style.setProperty(
            '--mouse-y',
            0 + "%"
          )
        }
        setDefault(1);
      }
    }catch(error){
      console.error(error);
    }
    const moveGradient = (e)=>{
      const winWidth = window.innerWidth;
      const winHeight = window.innerHeight;

      const mouseX = Math.round((e.pageX / winWidth) * 100);
      const mouseY = Math.round((e.pageY / winHeight) * 100);
      try{
        if(appRef){
          appRef.current.style.setProperty(
            '--mouse-x',
            mouseX.toString() + "%"
          )
          appRef.current.style.setProperty(
            '--mouse-y',
            mouseY.toString() + "%"
          )
        }
      }catch(error){
        console.error(error);
      }
      
    };
    document.addEventListener("mousemove",moveGradient);
    return function cleanup(){
      document.removeEventListener("mousemove",moveGradient);
    };
  },[appRef]);
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <div ref={appRef} className={styles.filterObj}></div>
          <h1 className='text-[10em] font-bold'>NeonBlogs</h1>
        </div>

        <div className={styles.grid}>
          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about everything you need in Blogs using&nbsp;BlogPost.
            </p>
          </a>

          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about varous things in each and every blog with&nbsp;BlogPost!
            </p>
          </a>

          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover boilerplate example&nbsp;projects.
            </p>
          </a>

          <a
            
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Post <span>-&gt;</span>
            </h2>
            <p>
              Instantly post your Next Blog Page to a shareable URL
              with&nbsp;BlogPost.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
