import React, { useEffect } from 'react'

import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import {useDispatch , useSelector} from 'react-redux';
import style2 from '@/styles/About.module.css'
import { logout } from '@/src/actions/userActions';
import { useRouter } from 'next/router';
const inter = Inter({ subsets: ['latin'] })

export default function About(){
    const dispatch = useDispatch();
    const router = useRouter();
    useEffect(()=>{
        dispatch(logout());
        router.push("/");
    });
  return (
    <>
        <Head>
        <title>Logout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center} style={{display:`flex` ,gap:`20px`, flexDirection:'column'}}>
          <h1 style={{fontSize:"9em"}}>Logging out...</h1>
        </div>
      </main>
    </>
  )
}
